package trie_test

import "testing"

func TestNoop(t *testing.T) {
	if false {
		t.Error("Something has gone horribly wrong")
	}
}
